
# Aliases
alias ls='ls -G'
alias ll='ls -n'
alias lsa='ls -A'
alias lla='ll -A'
alias rl='exec $SHELL -l'
alias cl='clear'
alias h='history -30'
alias hg='history -1000 | grep'
alias dsstore="find . -name '*.DS_Store' -type f -ls -delete"
alias rm='rm -r -i'
alias md='mkdir'
alias dot='cd ~/dotfiles'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ga='git add .'
alias gd='git diff'
alias gs='git status'
alias gp='git push'
alias gb='git branch'
alias gst='git status'
alias gco='git checkout'
alias gf='git fetch'
alias gc='git commit --allow-empty-message'
alias gcl='git clean -i'
alias python='python3'
alias code='nvim'
alias atom='nvim'
alias emacs='nvim'
alias edit='nvim'

# Global aliases
alias -g G='| grep --color=auto'
alias -g H='| head'
alias -g T='| tail'
