# add line above prompt
add_newline = true

# format of left prompt
format = """
$directory\
$git_branch\
$git_status\
\n$character\
"""

# format of right prompt
right_format = """
$cmd_duration\
$time\
"""

[directory]
truncation_length = 1

[character]
error_symbol = "[>](bold red)"
success_symbol = "[>](bold green)"
vimcmd_symbol = "[<](bold green)"
vimcmd_replace_one_symbol = "[<](bold purple)"
vimcmd_visual_symbol = "[<](bold yellow)"

[git_branch]
format = "[$branch ]($style)"
style = "fg:red"

[git_status]
conflicted = "conflicted"
ahead = "ahead"
behind = "behind"
diverged = "diverged"
untracked = "untracked"
stashed = "stashed"
modified = "modified"
staged = "staged"
renamed = "renamed"
deleted = "deleted"

[cmd_duration]
min_time = 100
show_milliseconds = true
format = "[$duration]($style)"

[time]
disabled = false
format = " [$time]($style)"
time_format = "%R"
style = "blink white"
